using System;
using System.Collections.Generic;
using DOL.Database;

namespace DOL.GS
{
    /// <summary>
    /// Item templates whose realm does not match their model's realm (generated by
    /// tools/claude-version/cross_realm_gear_audit.py from the client's objects.csv). A Midgard hat on
    /// a Hibernia model has no Valkyn or Troll mesh, so it does not fit; weapons and
    /// shields just look like another realm's. Bots never pick these when equipping;
    /// the items stay in the database for players.
    /// </summary>
    public static class BotCrossRealmGear
    {
        private static readonly HashSet<string> ExcludedTemplateIds = new(StringComparer.OrdinalIgnoreCase)
        {
            "adamantium_exceptional_mace", // Albion item on model 915 'Hib Dire Mace'
            "adamantium_exceptional_partisan", // Albion item on model 2689 'Hib Placeholder celtic spear'
            "adamantium_exceptional_war_pick", // Albion item on model 940 'Hib Adze'
            "adamantium_fortified_hammer", // Albion item on model 912 'Hib 2H Shod Shilelagh'
            "adamantium_reinforced_lamellar_helm", // Albion item on model 2388 'TOA Volcanus Studded Helm 3 (Mid)'
            "adamantium_reinforced_lamellar_vest", // Albion item on model 1800 'Aerus Studded Body Hibernia'
            "adamantium_war_mace", // Albion item on model 905 'Hib 2H Mace'
            "adamantium_war_pick", // Albion item on model 2684 'Hib Placeholder 1 hd pierce'
            "asterite_exceptional_great_hammer", // Albion item on model 941 'Hib Barbed Adze'
            "asterite_exceptional_mace", // Albion item on model 917 'Hib Firbolg 2H Mace'
            "asterite_exceptional_rapier", // Albion item on model 2686 'Hib Placeholder 1hd pierce - vampiir unique'
            "asterite_fortified_mace", // Albion item on model 906 'Hib 2H Dire Club'
            "asterite_fortified_short_sword", // Albion item on model 943 'Hib Lurikeen Dagger'
            "asterite_guarded_rapier", // Albion item on model 945 'Hib Lurkeen Duel Rapier'
            "asterite_reinforced_lamellar_helm", // Albion item on model 2386 'TOA Volcanus Studded Helm 1 (Mid)'
            "asterite_reinforced_lamellar_vest", // Albion item on model 1758 'Stygia Studded Body Midgard'
            "Brimstone_Great_Hammer_of_Bedlam", // Albion item on model 904 'Hib 2H Hammer'
            "Brimstone_Shield_of_Chaos", // Albion item on model 1138 'Mid Great Grave Shield Metal'
            "buckler8", // Albion item on model 1048 'Hib  Wood Buckler'
            "d2_starter_scythe", // Albion item on model 931 'Hib Scythe'
            "Dura`ek`s Imbued Stave", // Albion item on model 3567 'Mid Mauler Champion Staff'
            "elm_buckler8", // Albion item on model 1048 'Hib  Wood Buckler'
            "elm_large_block_shield8", // Albion item on model 1066 'Hib  Wood LBlock'
            "elm_large_heater_shield8", // Albion item on model 1075 'Hib  Wood LHeater'
            "elm_large_round_shield8", // Albion item on model 1084 'Hib  Wood LRound'
            "elm_medium_block_shield8", // Albion item on model 1093 'Hib  Wood MBlock'
            "elm_medium_heater_shield8", // Albion item on model 1057 'Hib  Wood Heater'
            "elm_medium_round_shield8", // Albion item on model 1102 'Hib  Wood MRound'
            "embossed_buckler8", // Albion item on model 1046 'Hib  Leather Buckler'
            "embossed_large_block_shield8", // Albion item on model 1064 'Hib  Leather LBlock'
            "embossed_large_heater_shield8", // Albion item on model 1073 'Hib  Leather LHeater'
            "embossed_large_round_shield8", // Albion item on model 1082 'Hib  Leather LRound'
            "embossed_medium_block_shield8", // Albion item on model 1091 'Hib  Leather MBlock'
            "embossed_medium_heater_shield8", // Albion item on model 1055 'Hib  Leather Heater'
            "embossed_medium_round_shield8", // Albion item on model 1100 'Hib  Leather MRound'
            "Gladius_of_the_Battlelord", // Albion item on model 903 'Hib Leaf Short Sword'
            "Golestandt`s Fire", // Albion item on model 3924 'Mid DragonSlayer Long Bow'
            "Golestandts_Fire", // Albion item on model 3924 'Mid DragonSlayer Long Bow'
            "hard_buckler8", // Albion item on model 1046 'Hib  Leather Buckler'
            "hard_large_block_shield8", // Albion item on model 1064 'Hib  Leather LBlock'
            "hard_large_heater_shield8", // Albion item on model 1073 'Hib  Leather LHeater'
            "hard_large_round_shield8", // Albion item on model 1082 'Hib  Leather LRound'
            "hard_medium_block_shield8", // Albion item on model 1091 'Hib  Leather MBlock'
            "hard_medium_heater_shield8", // Albion item on model 1055 'Hib  Leather Heater'
            "hard_medium_round_shield8", // Albion item on model 1100 'Hib  Leather MRound'
            "large_block_shield8", // Albion item on model 1066 'Hib  Wood LBlock'
            "large_heater_shield8", // Albion item on model 1075 'Hib  Wood LHeater'
            "large_round_shield8", // Albion item on model 1084 'Hib  Wood LRound'
            "medium_block_shield8", // Albion item on model 1093 'Hib  Wood MBlock'
            "medium_heater_shield8", // Albion item on model 1057 'Hib  Wood Heater'
            "medium_round_shield8", // Albion item on model 1102 'Hib  Wood MRound'
            "netherium_exceptional_hammer", // Albion item on model 904 'Hib 2H Hammer'
            "netherium_exceptional_mace", // Albion item on model 914 'Hib Celtic Mace'
            "netherium_exceptional_short_sword", // Albion item on model 897 'Hib Elven Short Sword'
            "netherium_fortified_great_sword", // Albion item on model 2674 'Mid Placeholder two handed sword'
            "netherium_fortified_mace", // Albion item on model 914 'Hib Celtic Mace'
            "netherium_fortified_short_sword", // Albion item on model 897 'Hib Elven Short Sword'
            "netherium_guarded_rapier", // Albion item on model 945 'Hib Lurkeen Duel Rapier'
            "netherium_reinforced_lamellar_helm", // Albion item on model 2280 'TOA Oceanus Studded Helm 3 (Mid)'
            "netherium_war_pick", // Albion item on model 947 'Hib War Adze'
            "oak_large_block_shield8", // Albion item on model 1066 'Hib  Wood LBlock'
            "oak_large_heater_shield8", // Albion item on model 1075 'Hib  Wood LHeater'
            "oak_large_round_shield8", // Albion item on model 1084 'Hib  Wood LRound'
            "oak_medium_block_shield8", // Albion item on model 1093 'Hib  Wood MBlock'
            "oak_medium_heater_shield8", // Albion item on model 1057 'Hib  Wood Heater'
            "oak_medium_round_shield8", // Albion item on model 1102 'Hib  Wood MRound'
            "oaken_buckler8", // Albion item on model 1048 'Hib  Wood Buckler'
            "Old_Defender_of_Scorched_Dreams", // Albion item on model 1161 'Hib Leaf Point Shield Wood'
            "rigid_buckler8", // Albion item on model 1046 'Hib  Leather Buckler'
            "rigid_large_block_shield8", // Albion item on model 1064 'Hib  Leather LBlock'
            "rigid_large_heater_shield8", // Albion item on model 1073 'Hib  Leather LHeater'
            "rigid_large_round_shield8", // Albion item on model 1082 'Hib  Leather LRound'
            "rigid_medium_block_shield8", // Albion item on model 1091 'Hib  Leather MBlock'
            "rigid_medium_heater_shield8", // Albion item on model 1055 'Hib  Leather Heater'
            "rigid_medium_round_shield8", // Albion item on model 1100 'Hib  Leather MRound'
            "Sarcondina Polished Shield", // Albion item on model 2727 'Possessed Midgard large shield'
            "Sigil_Ensorcelled_Mail_Hauberk", // Albion item on model 2713 'Possessed Midgard chain/scale chest'
            "2_FDK_Shield", // Midgard item on model 1117 'Alb Kite Shield Metal'
            "adamantium_battle_spear2", // Midgard item on model 2689 'Hib Placeholder celtic spear'
            "adamantium_exceptional_double_bladed_axe2", // Midgard item on model 145 'Albion Gravestone'
            "adamantium_exceptional_hooked_spear2", // Midgard item on model 936 'Hib Firbolg Spear'
            "adamantium_fortified_great_hammer2", // Midgard item on model 842 'Alb 2H Blunt'
            "adamantium_heavy_starkaskodd_boots2", // Midgard item on model 2807 'Good Albion studded/reinforced boots'
            "adamantium_heavy_starkaskodd_helm2", // Midgard item on model 2316 'TOA Stygia Studded Helm 3 (Alb)'
            "adamantium_heavy_starkaskodd_sleeves2", // Midgard item on model 2805 'Good Albion studded/reinforced sleeves'
            "adamantium_superior_war_circlet2", // Midgard item on model 1294 'Tiara Cloth - Alb'
            "adamantium_weighted_double_bladed_axe2", // Midgard item on model 145 'Albion Gravestone'
            "amber_encrusted_ivy_wreath3", // Midgard item on model 1292 'Tiara - Hib'
            "antlered_helm3", // Midgard item on model 1288 'Hib Stag Helm'
            "Arcanium_Antioos_Shield", // Midgard item on model 1123 'Alb Tower Shield Metal'
            "Arcanium_Imsetys_Shield_of_Dread", // Midgard item on model 1123 'Alb Tower Shield Metal'
            "Arcanium_Magma_Infused_Defender", // Midgard item on model 1123 'Alb Tower Shield Metal'
            "Arcanium_Sentient_Tower_Shield", // Midgard item on model 1123 'Alb Tower Shield Metal'
            "asterite_dwarven_great_sword", // Midgard item on model 843 'Alb 2H Slash'
            "asterite_dwarven_great_sword2", // Midgard item on model 843 'Alb 2H Slash'
            "asterite_exceptional_great_sword2", // Midgard item on model 2690 'Hib Placeholder large weapon blade'
            "asterite_exceptional_pick_hammer2", // Midgard item on model 913 'Hib Celtic Hammer'
            "asterite_fortified_battle_axe2", // Midgard item on model 2657 'Alb Placeholder Slash'
            "asterite_fortified_long_sword2", // Midgard item on model 896 'Hib Elven Long Sword'
            "asterite_heavy_starkakedja_helm2", // Midgard item on model 2299 'TOA Oceanus Scale Helm 1 (Hib)'
            "asterite_heavy_starkakedja_leggings2", // Midgard item on model 2810 'Good Albion chain/scale leggings'
            "asterite_heavy_starkaskodd_boots2", // Midgard item on model 731 'Albion Scout Boots'
            "asterite_heavy_starkaskodd_helm2", // Midgard item on model 2370 'TOA Volcanus Studded Helm 3 (Alb)'
            "asterite_heavy_starkaskodd_sleeves2", // Midgard item on model 2743 'Possessed Albion studded/reinforced sleeves'
            "asterite_heavy_starkaskodd_vest2", // Midgard item on model 1782 'Volcanus Studded Body Hibernia'
            "asterite_superior_spiked_circlet2", // Midgard item on model 1295 'Tiara  Leather - Alb'
            "asterite_superior_war_circlet2", // Midgard item on model 1294 'Tiara Cloth - Alb'
            "asterite_weighted_hooked_spear2", // Midgard item on model 936 'Hib Firbolg Spear'
            "basalt_bow_of_bedlam2", // Midgard item on model 925 'Hib Recurve Long Bow'
            "Befouled Arcanium Labyrinth Circlet", // Midgard item on model 1292 'Tiara - Hib'
            "Benthic_Magus_Staff2", // Midgard item on model 1968 'Albion Mage Staff 01 Water'
            "bone_encrusted_ivy_wreath3", // Midgard item on model 1292 'Tiara - Hib'
            "Brilliant Jotun Blackorm Coif", // Midgard item on model 63 'Albion Chain Helmet 1 (Cap)'
            "brocade_woven_pointed_steeple_hat3", // Midgard item on model 1279 'Gandalf Hat Hibernia'
            "brocade_woven_wreath3", // Midgard item on model 1298 'Tiara Cloth - Hib'
            "Brutal_Bearguard", // Midgard item on model 1123 'Alb Tower Shield Metal'
            "cailiocht_helm3", // Midgard item on model 827 'Hibernia Studded Cap'
            "carbide_mistletoe_spiked_wreath3", // Midgard item on model 1292 'Tiara - Hib'
            "Cianans_Cataclysmic_Shield", // Midgard item on model 1123 'Alb Tower Shield Metal'
            "cobalt_mistletoe_spiked_wreath3", // Midgard item on model 1292 'Tiara - Hib'
            "Corrupted Silksteel Labyrinth Circlet", // Midgard item on model 1292 'Tiara - Hib'
            "cured_suede_wreath3", // Midgard item on model 1299 'Tiara  Leather- Hib'
            "dolomite_mistletoe_spiked_wreath3", // Midgard item on model 1292 'Tiara - Hib'
            "Dragon_Singed_Ebon_Coif", // Midgard item on model 63 'Albion Chain Helmet 1 (Cap)'
            "duskwood_exceptional_block_shield2", // Midgard item on model 1065 'Hib  Metal LBlock'
            "duskwood_exceptional_buckler2", // Midgard item on model 1047 'Hib  Metal Buckler'
            "duskwood_exceptional_heater_shield2", // Midgard item on model 1056 'Hib  Metal Heater'
            "duskwood_exceptional_large_round_shield2", // Midgard item on model 1083 'Hib  Metal LRound'
            "duskwood_exceptional_magus_staff2", // Midgard item on model 1180 'Hib Staff 08'
            "dyrwood_exceptional_block_shield2", // Midgard item on model 1065 'Hib  Metal LBlock'
            "dyrwood_exceptional_buckler2", // Midgard item on model 1047 'Hib  Metal Buckler'
            "dyrwood_exceptional_heater_shield2", // Midgard item on model 1056 'Hib  Metal Heater'
            "dyrwood_exceptional_large_round_shield2", // Midgard item on model 1083 'Hib  Metal LRound'
            "dyrwood_exceptional_magus_staff2", // Midgard item on model 1180 'Hib Staff 08'
            "ebonwood_exceptional_block_shield2", // Midgard item on model 1065 'Hib  Metal LBlock'
            "ebonwood_exceptional_buckler2", // Midgard item on model 1047 'Hib  Metal Buckler'
            "ebonwood_exceptional_heater_shield2", // Midgard item on model 1056 'Hib  Metal Heater'
            "ebonwood_exceptional_large_round_shield2", // Midgard item on model 1083 'Hib  Metal LRound'
            "ebonwood_exceptional_magus_staff2", // Midgard item on model 1180 'Hib Staff 08'
            "elegant_moss-trimmed_tunic3", // Midgard item on model 1332 'Hib Rp Basic Set 1 Tunic'
            "embossed_suede_wreath3", // Midgard item on model 1299 'Tiara  Leather- Hib'
            "empyrean_bonewalkers_staff", // Midgard item on model 1175 'Hib Staff 03'
            "encrusted_ivy_wreath3", // Midgard item on model 1292 'Tiara - Hib'
            "entwined_leaf_hat3", // Midgard item on model 1285 'Hib Leaf Hat'
            "exquisite_moss-trimmed_tunic3", // Midgard item on model 1336 'Hib Rp Basic Set 2 Tunic'
            "ferrite_mistletoe_spiked_wreath3", // Midgard item on model 1292 'Tiara - Hib'
            "Fortifying Long Spear", // Midgard item on model 935 'Hib Elven Spear'
            "fossil_encrusted_ivy_wreath3", // Midgard item on model 1292 'Tiara - Hib'
            "gossamer_superior_padded_steeple_hat2", // Midgard item on model 1278 'Gandalf Hat Albion'
            "gossamer_woven_pointed_steeple_hat3", // Midgard item on model 1279 'Gandalf Hat Hibernia'
            "gossamer_woven_wreath3", // Midgard item on model 1298 'Tiara Cloth - Hib'
            "great_war_scythe3", // Midgard item on model 928 'Hib Greatwar Scythe'
            "hard_suede_wreath3", // Midgard item on model 1299 'Tiara  Leather- Hib'
            "harvest_scythe3", // Midgard item on model 929 'Hib Harvest Scythe'
            "heartwood_exceptional_block_shield2", // Midgard item on model 1065 'Hib  Metal LBlock'
            "heartwood_exceptional_buckler2", // Midgard item on model 1047 'Hib  Metal Buckler'
            "heartwood_exceptional_heater_shield2", // Midgard item on model 1056 'Hib  Metal Heater'
            "heartwood_exceptional_large_round_shield2", // Midgard item on model 1083 'Hib  Metal LRound'
            "heartwood_exceptional_magus_staff2", // Midgard item on model 1180 'Hib Staff 08'
            "linen_woven_pointed_steeple_hat3", // Midgard item on model 1279 'Gandalf Hat Hibernia'
            "linen_woven_wreath3", // Midgard item on model 1298 'Tiara Cloth - Hib'
            "martial_scythe3", // Midgard item on model 930 'Hib Martial Scythe'
            "mistletoe_spiked_wreath3", // Midgard item on model 1292 'Tiara - Hib'
            "moss-trimmed_boots3", // Midgard item on model 1333 'Hib Rp Basic Set 1 Boots'
            "moss-trimmed_gloves3", // Midgard item on model 1334 'Hib Rp Basic Set 1 Gloves'
            "moss-trimmed_leggings3", // Midgard item on model 1335 'Hib Rp Basic Set 1 Legs'
            "Muck-Covered_Fish_Scale", // Midgard item on model 1123 'Alb Tower Shield Metal'
            "netherium_exceptional_double_bladed_axe2", // Midgard item on model 145 'Albion Gravestone'
            "netherium_fortified_great_hammer2", // Midgard item on model 844 'Alb 2H Blunt'
            "netherium_fortified_great_sword2", // Midgard item on model 847 'Alb 2H Slash'
            "netherium_fortified_pick_hammer2", // Midgard item on model 855 'Alb Coffin Hammer Mace'
            "netherium_heavy_starkakedja_sleeves2", // Midgard item on model 2786 'Possessed Hibernia plate sleeves'
            "netherium_heavy_starkaskodd_helm2", // Midgard item on model 2806 'Good Albion studded/reinforced helm'
            "netherium_superior_war_circlet2", // Midgard item on model 1290 'Tiara - Alb'
            "offline50_20260904_c30_s12_t8", // Midgard item on model 1168 'Albion Mage Staff 03'
            "Old Bewitched Dracon Shield", // Midgard item on model 1123 'Alb Tower Shield Metal'
            "Old Bewitched Draconic Shield", // Midgard item on model 1123 'Alb Tower Shield Metal'
            "Old Great Shadowed Impaler", // Midgard item on model 919 'Hib Celtic Great Bow'
            "quartz_mistletoe_spiked_wreath3", // Midgard item on model 1292 'Tiara - Hib'
            "rawhide_suede_wreath3", // Midgard item on model 1299 'Tiara  Leather- Hib'
            "resplendent_moss-trimmed_tunic3", // Midgard item on model 1337 'Hib Rp Basic Set 3 Tunic'
            "rigid_suede_wreath3", // Midgard item on model 1299 'Tiara  Leather- Hib'
            "runewood_exceptional_block_shield2", // Midgard item on model 1059 'Alb  Metal LBlock'
            "runewood_exceptional_buckler2", // Midgard item on model 1047 'Hib  Metal Buckler'
            "runewood_exceptional_heater_shield2", // Midgard item on model 1050 'Alb  Metal Heater'
            "runewood_exceptional_large_round_shield2", // Midgard item on model 1077 'Alb  Metal LRound'
            "runewood_exceptional_magus_staff2", // Midgard item on model 1180 'Hib Staff 08'
            "scythe3", // Midgard item on model 931 'Hib Scythe'
            "shell_encrusted_ivy_wreath3", // Midgard item on model 1292 'Tiara - Hib'
            "silk_woven_pointed_steeple_hat3", // Midgard item on model 1279 'Gandalf Hat Hibernia'
            "silk_woven_wreath3", // Midgard item on model 1298 'Tiara Cloth - Hib'
            "stonewood_exceptional_block_shield2", // Midgard item on model 1065 'Hib  Metal LBlock'
            "stonewood_exceptional_buckler2", // Midgard item on model 1047 'Hib  Metal Buckler'
            "stonewood_exceptional_heater_shield2", // Midgard item on model 1056 'Hib  Metal Heater'
            "stonewood_exceptional_large_round_shield2", // Midgard item on model 1083 'Hib  Metal LRound'
            "stonewood_exceptional_magus_staff2", // Midgard item on model 1180 'Hib Staff 08'
            "sylvan_woven_pointed_steeple_hat3", // Midgard item on model 1279 'Gandalf Hat Hibernia'
            "sylvan_woven_wreath3", // Midgard item on model 1298 'Tiara Cloth - Hib'
            "tanned_suede_wreath3", // Midgard item on model 1299 'Tiara  Leather- Hib'
            "Tempestuous_Magus_Staff", // Midgard item on model 1965 'Albion Mage Staff 01 Air'
            "Triumphant_Scout_Stone_Shaper", // Midgard item on model 3960 'Alb DragonSlayer Long Bow'
            "Vendo_Blade_Blocker", // Midgard item on model 1117 'Alb Kite Shield Metal'
            "vine_encrusted_ivy_wreath3", // Midgard item on model 1292 'Tiara - Hib'
            "vom_vendo_bone_studded_helm", // Midgard item on model 824 'Albion Studded Helm'
            "war_scythe3", // Midgard item on model 932 'Hib War Scythe'
            "woolen_woven_pointed_steeple_hat3", // Midgard item on model 1279 'Gandalf Hat Hibernia'
            "woolen_woven_wreath3", // Midgard item on model 1298 'Tiara Cloth - Hib'
            "3_Glimmerstrike_Shield", // Hibernia item on model 3965 'Alb DragonSlayer Small Shield'
            "Arcanite_Azars_Defense", // Hibernia item on model 1123 'Alb Tower Shield Metal'
            "Arcanite_Greater_Aerial_Defender", // Hibernia item on model 1123 'Alb Tower Shield Metal'
            "Arcanite_Gusting_Great_Leaf_Shield", // Hibernia item on model 1123 'Alb Tower Shield Metal'
            "Arcanite_Hermes_Golden_Shield", // Hibernia item on model 1123 'Alb Tower Shield Metal'
            "Arcanite_Scaly_Block_Shield", // Hibernia item on model 1123 'Alb Tower Shield Metal'
            "Arcanite_Sinovias_Block", // Hibernia item on model 1123 'Alb Tower Shield Metal'
            "Arcanite_Sinovias_Shield", // Hibernia item on model 1123 'Alb Tower Shield Metal'
            "Ard_Targaid", // Hibernia item on model 2725 'Possessed Midgard small shield'
            "Basalt_Buckler_of_Oblivion", // Hibernia item on model 1126 'Mid Crescent Shield Metal'
            "Basalt_Mace_of_Anarchy3", // Hibernia item on model 853 'Alb Avalonian Mace'
            "Benthic_Short_Sword", // Hibernia item on model 1944 'Alb Cinquedea Water'
            "Brimstone_Dagger_of_Bedlam", // Hibernia item on model 885 'Alb Duelists Dagger'
            "Brimstone_Shield_of_Chaos2", // Hibernia item on model 1138 'Mid Great Grave Shield Metal'
            "chitin_embossed_jewelry_box3", // Hibernia item on model 1548 'ext outhouse mid'
            "Cursed_Shield_of_Heeun", // Hibernia item on model 1123 'Alb Tower Shield Metal'
            "Dobs_Bloody_Fang", // Hibernia item on model 889 'Alb Highlander Dirk'
            "duskwood_exceptional_block_shield3", // Hibernia item on model 1062 'Mid  Metal LBlock'
            "duskwood_exceptional_buckler3", // Hibernia item on model 1044 'Mid  Metal Buckler'
            "duskwood_exceptional_heater_shield3", // Hibernia item on model 1053 'Mid  Metal Heater'
            "duskwood_exceptional_large_round_shield3", // Hibernia item on model 1080 'Mid  Metal LRound'
            "dyrwood_exceptional_block_shield3", // Hibernia item on model 1062 'Mid  Metal LBlock'
            "dyrwood_exceptional_buckler3", // Hibernia item on model 1044 'Mid  Metal Buckler'
            "dyrwood_exceptional_heater_shield3", // Hibernia item on model 1053 'Mid  Metal Heater'
            "dyrwood_exceptional_large_round_shield3", // Hibernia item on model 1080 'Mid  Metal LRound'
            "ebonwood_exceptional_block_shield3", // Hibernia item on model 1062 'Mid  Metal LBlock'
            "ebonwood_exceptional_buckler3", // Hibernia item on model 1044 'Mid  Metal Buckler'
            "ebonwood_exceptional_heater_shield3", // Hibernia item on model 1053 'Mid  Metal Heater'
            "ebonwood_exceptional_large_round_shield3", // Hibernia item on model 1080 'Mid  Metal LRound'
            "Enchanted_Woven_Pants", // Hibernia item on model 2167 'Volcanus Cloth Legs Alb/Mid'
            "Ghostly Truesilver Battle Jerkin", // Hibernia item on model 2135 'Stygia Leather Body(Alb)'
            "Glimmer Spirit Sword", // Hibernia item on model 2671 'Mid Placeholder sword'
            "heartwood_exceptional_block_shield3", // Hibernia item on model 1062 'Mid  Metal LBlock'
            "heartwood_exceptional_buckler3", // Hibernia item on model 1044 'Mid  Metal Buckler'
            "heartwood_exceptional_heater_shield3", // Hibernia item on model 1053 'Mid  Metal Heater'
            "heartwood_exceptional_large_round_shield3", // Hibernia item on model 1080 'Mid  Metal LRound'
            "leaf_embossed_jewelry_box3", // Hibernia item on model 1548 'ext outhouse mid'
            "Malevolent_Darkspire_Aegis", // Hibernia item on model 1123 'Alb Tower Shield Metal'
            "runewood_exceptional_block_shield3", // Hibernia item on model 1059 'Alb  Metal LBlock'
            "runewood_exceptional_buckler3", // Hibernia item on model 1044 'Mid  Metal Buckler'
            "runewood_exceptional_heater_shield3", // Hibernia item on model 1050 'Alb  Metal Heater'
            "runewood_exceptional_large_round_shield3", // Hibernia item on model 1077 'Alb  Metal LRound'
            "Speedy_Tower_Shield", // Hibernia item on model 1123 'Alb Tower Shield Metal'
            "stonewood_exceptional_block_shield3", // Hibernia item on model 1062 'Mid  Metal LBlock'
            "stonewood_exceptional_buckler3", // Hibernia item on model 1044 'Mid  Metal Buckler'
            "stonewood_exceptional_heater_shield3", // Hibernia item on model 1053 'Mid  Metal Heater'
            "stonewood_exceptional_large_round_shield3", // Hibernia item on model 1080 'Mid  Metal LRound'
            "Tempestuous_Magus_Staff3", // Hibernia item on model 2065 'Mid Staff 04 Air'
            "Tempestuous_Short_Sword", // Hibernia item on model 1941 'Alb Cinquedea Air'
        };

        public static int Count => ExcludedTemplateIds.Count;

        public static bool IsExcluded(DbItemTemplate template) =>
            template != null && !string.IsNullOrEmpty(template.Id_nb) && ExcludedTemplateIds.Contains(template.Id_nb);
    }
}
