-- Offline DAoC 0.35 world: Battleground. Generated by tools/world/derive-world-delta.py; do not edit by hand.
INSERT OR REPLACE INTO "Battleground" ("RegionID","MinLevel","MaxLevel","MaxRealmLevel","LastTimeRowUpdated","Battleground_ID") VALUES (250,30,35,25,'2000-01-01 00:00:00','Caledonia (Level 34-39 - RR3L5)');
