-- Offline DAoC 0.35 world: TaskRefreshIntervals. Generated by tools/world/derive-world-delta.py; do not edit by hand.
INSERT OR REPLACE INTO "TaskRefreshIntervals" ("LastRollover","RolloverInterval","DailyTaskRolloverTime_ID","LastTimeRowUpdated") VALUES ('2026-10-08 00:00:57.3526535','DAILY',1,'2026-10-08 04:00:57.3532343Z');
INSERT OR REPLACE INTO "TaskRefreshIntervals" ("LastRollover","RolloverInterval","DailyTaskRolloverTime_ID","LastTimeRowUpdated") VALUES ('2026-10-07 00:00:00.0145676','WEEKLY',2,'2026-10-07 04:00:00.0146528Z');
INSERT OR REPLACE INTO "TaskRefreshIntervals" ("LastRollover","RolloverInterval","DailyTaskRolloverTime_ID","LastTimeRowUpdated") VALUES ('2026-10-01 00:00:00.0269477','MONTHLY',3,'2026-10-01 04:00:00.0270948Z');
