-- Offline DAoC 0.35 world: Relic. Generated by tools/world/derive-world-delta.py; do not edit by hand.
INSERT OR REPLACE INTO "Relic" ("RelicID","Region","X","Y","Z","Heading","Realm","OriginalRealm","LastRealm","relicType","LastCaptureDate","LastTimeRowUpdated","Relic_ID") VALUES (25,1,506652,308796,7664,555,1,1,1,1,'2025-09-04 07:53:58','2026-10-08 06:43:45.9093894Z','25');
