-- Offline DAoC 0.35 world: offline_world_migrations. Generated by tools/world/derive-world-delta.py; do not edit by hand.
CREATE TABLE IF NOT EXISTS offline_world_migrations (
    MigrationId TEXT PRIMARY KEY,
    AppliedUtc TEXT NOT NULL,
    Description TEXT NOT NULL,
    ArchivedRows INTEGER NOT NULL
);
INSERT OR REPLACE INTO "offline_world_migrations" ("MigrationId","AppliedUtc","Description","ArchivedRows") VALUES ('classic165-legacy-spawns-v1','2026-08-29T03:12:24.9276935Z','Reproducible Classic/SI authority: retain legacy DOL neutral spawns and all service/scripted/custom NPCs; archive later generic neutral Atlas additions.',58521);
INSERT OR REPLACE INTO "offline_world_migrations" ("MigrationId","AppliedUtc","Description","ArchivedRows") VALUES ('classic165-si-darkness-falls-spawns-v1','2026-08-29T15:23:36.4494363Z','Restore archived Shrouded Isles and Classic Darkness Falls progression; SI and region 249 are outside the Classic overpopulation cleanup boundary.',18726);
INSERT OR REPLACE INTO "offline_world_migrations" ("MigrationId","AppliedUtc","Description","ArchivedRows") VALUES ('classic165-conservative-frontier-albion-spawns-v1','2026-09-06T19:17:24.4304916Z','Restore only archive rows corroborated by CapnBry or the 2002 Kirstena Cruachan map, cap source camps at two rows, and require installed-navmesh route validation.',983);
INSERT OR REPLACE INTO "offline_world_migrations" ("MigrationId","AppliedUtc","Description","ArchivedRows") VALUES ('classic165-period-map-frontier-albion-spawns-v2','2026-09-06T20:33:14.9986446Z','Restore only archived rows corroborated by 2002 Kirstena/Illia maps, CapnBry coordinates, or period Mount Collory/Cruachan reports; preserve original templates and require bidirectional installed-navmesh validation.',1290);
