-- Offline DAoC 0.33 world: Relic. Generated by tools/world/derive-033-delta.py; do not edit by hand.
INSERT OR REPLACE INTO "Relic" ("RelicID","Region","X","Y","Z","Heading","Realm","OriginalRealm","LastRealm","relicType","LastCaptureDate","LastTimeRowUpdated","Relic_ID") VALUES (25,1,506652,308796,7664,555,1,1,1,1,'2025-09-04 07:53:58','2026-09-30 03:58:20.625718Z','25');
