-- Offline DAoC 0.33 world: TaskRefreshIntervals. Generated by tools/world/derive-033-delta.py; do not edit by hand.
INSERT OR REPLACE INTO "TaskRefreshIntervals" ("LastRollover","RolloverInterval","DailyTaskRolloverTime_ID","LastTimeRowUpdated") VALUES ('2026-09-29 00:08:00.4624061','DAILY',1,'2026-09-29 04:08:00.4628611Z');
INSERT OR REPLACE INTO "TaskRefreshIntervals" ("LastRollover","RolloverInterval","DailyTaskRolloverTime_ID","LastTimeRowUpdated") VALUES ('2026-09-29 00:08:00.4647062','WEEKLY',2,'2026-09-29 04:08:00.4648175Z');
INSERT OR REPLACE INTO "TaskRefreshIntervals" ("LastRollover","RolloverInterval","DailyTaskRolloverTime_ID","LastTimeRowUpdated") VALUES ('2026-09-01 00:00:00.046674','MONTHLY',3,'2026-09-01 04:00:00.0507489Z');
