-- Offline DAoC 0.33 world: offline_auction_settings. Generated by tools/world/derive-033-delta.py; do not edit by hand.
CREATE TABLE IF NOT EXISTS offline_auction_settings (
    Key TEXT PRIMARY KEY,
    Value TEXT NOT NULL,
    Description TEXT NOT NULL
);
INSERT OR REPLACE INTO "offline_auction_settings" ("Key","Value","Description") VALUES ('LocationRegionId','','Intentionally unset until the owner chooses the auction-house location.');
INSERT OR REPLACE INTO "offline_auction_settings" ("Key","Value","Description") VALUES ('LocationX','','Intentionally unset until the owner chooses the auction-house location.');
INSERT OR REPLACE INTO "offline_auction_settings" ("Key","Value","Description") VALUES ('LocationY','','Intentionally unset until the owner chooses the auction-house location.');
INSERT OR REPLACE INTO "offline_auction_settings" ("Key","Value","Description") VALUES ('LocationZ','','Intentionally unset until the owner chooses the auction-house location.');
INSERT OR REPLACE INTO "offline_auction_settings" ("Key","Value","Description") VALUES ('DefaultListingHours','24','Default real-time listing duration.');
INSERT OR REPLACE INTO "offline_auction_settings" ("Key","Value","Description") VALUES ('Enabled','true','The real-item Realm Exchange is available through one broker in each capital city.');
INSERT OR REPLACE INTO "offline_auction_settings" ("Key","Value","Description") VALUES ('AlbionLocation','10,36200,30300,8000','Camelot City, beside the vault keepers.');
INSERT OR REPLACE INTO "offline_auction_settings" ("Key","Value","Description") VALUES ('MidgardLocation','101,32250,28250,8819','Jordheim, beside the vault keeper.');
INSERT OR REPLACE INTO "offline_auction_settings" ("Key","Value","Description") VALUES ('HiberniaLocation','201,32900,30950,8000','Tir na Nog, beside the vault keeper.');
INSERT OR REPLACE INTO "offline_auction_settings" ("Key","Value","Description") VALUES ('RequireRealInventoryItem','true','Every listing must be an actual persisted inventory item.');
INSERT OR REPLACE INTO "offline_auction_settings" ("Key","Value","Description") VALUES ('RequireRealCoinEscrow','true','Every purchase must transfer actual copper.');
INSERT OR REPLACE INTO "offline_auction_settings" ("Key","Value","Description") VALUES ('AllowSyntheticListings','false','Never generate fake items, bids, sales, or market activity.');
