-- Offline DAoC 0.33 world: offline_population_settings. Generated by tools/world/derive-033-delta.py; do not edit by hand.
CREATE TABLE IF NOT EXISTS offline_population_settings (
    Key TEXT PRIMARY KEY,
    Value TEXT NOT NULL,
    Description TEXT NOT NULL
);
INSERT OR REPLACE INTO "offline_population_settings" ("Key","Value","Description") VALUES ('HardActiveCap','0','Absolute first-stage safety limit for this PC.');
INSERT OR REPLACE INTO "offline_population_settings" ("Key","Value","Description") VALUES ('InitialCohortSize','3','First measured cohort: one fully active bot per realm.');
INSERT OR REPLACE INTO "offline_population_settings" ("Key","Value","Description") VALUES ('ExperienceRate','1.0','Original one-times experience multiplier.');
INSERT OR REPLACE INTO "offline_population_settings" ("Key","Value","Description") VALUES ('RulesetPatch','1.65','Classic pre-Trials of Atlantis balance target.');
INSERT OR REPLACE INTO "offline_population_settings" ("Key","Value","Description") VALUES ('MaximumExpansion','Shrouded Isles','Classic and Shrouded Isles content only.');
INSERT OR REPLACE INTO "offline_population_settings" ("Key","Value","Description") VALUES ('StartupRampMinutes','15','First third within five minutes; full requested roster by fifteen minutes.');
INSERT OR REPLACE INTO "offline_population_settings" ("Key","Value","Description") VALUES ('AllowCharacterDeletion','false','Shutdown, restart, and lower population targets only park characters; never delete progress, inventory, bank, equipment, or money.');
INSERT OR REPLACE INTO "offline_population_settings" ("Key","Value","Description") VALUES ('ActiveOnly','true','All progression requires a live bot actor performing real world actions.');
INSERT OR REPLACE INTO "offline_population_settings" ("Key","Value","Description") VALUES ('BackgroundProgression','false','Time-skipped and offline simulated progression is forbidden.');
INSERT OR REPLACE INTO "offline_population_settings" ("Key","Value","Description") VALUES ('AiBudgetMs','4.0','Stagger live bot thinking and defer excess AI work without simulating progress.');
INSERT OR REPLACE INTO "offline_population_settings" ("Key","Value","Description") VALUES ('WorldActorOnly','true','Every progressing bot must remain a real loaded world actor.');
INSERT OR REPLACE INTO "offline_population_settings" ("Key","Value","Description") VALUES ('PopulationEnabled','true','Master safety switch. Generated launcher characters enable this explicitly.');
INSERT OR REPLACE INTO "offline_population_settings" ("Key","Value","Description") VALUES ('ActiveTarget','0','Requested number of real world bot objects.');
